spring.application.name=talent360bank
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/talent360bank
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Recharge automatique des templates sans redemarrer le serveur (pratique en dev)
spring.thymeleaf.cache=false
